### ISSUE TITLE
Occasionally unable to select a prop despite conditions being ideal

### ISSUE THREAD

**Issue by exp** [Newbrict/ObjHunt#67]
Heya,
  So the last bug I have been able to find is that occasionally (and despite the halo appearing green, i'm colour blind as hell) I am unable to select a prop for some time until I have moved around a bunch.

  I'm not sure where this bug is coming from, but I thought I'd add it as an issue so any debugging can be added here.

Cheers

**Comment by Newbrict** [comment]
this should have been fixed
