### ISSUE TITLE
voice icon appears above props and custom models won't load of other players

### ISSUE THREAD

**Issue by LunarWing** [Newbrict/ObjHunt#77]
If a prop uses the mic to chat with people, a voice icon appears above there head.
How do I stop this from happening.

Also I have been trying to use custom default models for hunters and props.
The models show for me but, for everyone else all they can see is error.

I have edited the general config file and this is my code for it.
-- the default player models
TEAM_PROPS_DEFAULT_MODEL = "models/pokemon/gen4/479/rotom.mdl"
TEAM_HUNTERS_DEFAULT_MODEL = "models/rtbmodels/pokemonxy/brendan.mdl"

If you fell like helping a little more I have another issue which I think is unrelated to your mode.
Player models behave weirdly. The rotom for props looks off to the left and is halfway in the ground. The hunter prop holds there hands out like a T-post. A mdl, phy, and vvd file exists for both models and I believe these are the property files for them but I dont know how to fix this.

**Comment by Newbrict** [comment]
So the error model is occuring because the server isn't sending the model files to the client
you need them in fastdl server. or require them by the server from the workshop.

not sure about the voice icon, I'm sure other people have had and fixed this issue, google it.

**Comment by jonnyboy0719** [comment]
To get new custom models, you need to make sure it actually downloads to the player. You can do so by having an auto script adding the new models in (if they are on the same folder) or add them manually to the list.

But since you use custom models that don't exist in the same folder, its best you add them manually. And you need todo the same for its textures (include vmt and vtf extension)

Example ¤1:
```lua
-- Pokemon Gen 4 Model
resource.AddFile("models/pokemon/gen4/479/rotom.mdl")
resource.AddFile("models/pokemon/gen4/479/rotom.phy")
resource.AddFile("models/pokemon/gen4/479/rotom.dx80.vtx") -- Direct X 8 is no longer supported on the latest Source Engine, so this file can be deleted from the drive.
resource.AddFile("models/pokemon/gen4/479/rotom.dx90.vtx")
resource.AddFile("models/pokemon/gen4/479/rotom.sw.vtx")
resource.AddFile("models/pokemon/gen4/479/rotom.vvd")
```

Example ¤2 (if Workshop):
```lua
-- If the models exist on the workshop, then it will be easier for you.
--[[
       This gets the ID from workshop, example:
       http://steamcommunity.com/workshop/filedetails/?id=#ID
       
       And where it says #ID, thats where the ID goes. And our ID is 104606562. So thats what we are going to add!
--]]
resource.AddWorkshop( "104606562") -- Achievement viewer example.
```

**Comment by Newbrict** [comment]
@jonnyboy0719 :+1: very nice, thanks for helping him out!

**Comment by jonnyboy0719** [comment]
@Newbrict Happy to help! :smiley:

**Comment by LunarWing** [comment]
@jonnyboy0719 YOU ARE AN AMAZING PERSON!!!! Dont let ANYONE tell you otherwise!
