### ISSUE TITLE
Auto play taunt after some time

### ISSUE THREAD

**Issue by CSchulz** [Newbrict/ObjHunt#78]

**Comment by Newbrict** [comment]
yeah would be a good feature, feel free to try to code it up

**Comment by CSchulz** [comment]
There is already one implementation but the pull request is missing:

https://github.com/bsnuggs1/ObjHunt/commit/9526b9b41ca8d5ef65617ef8cc13b652d272c4db

**Comment by Newbrict** [comment]
done!
