### ISSUE TITLE
Unable to become anyprop

### ISSUE THREAD

**Issue by Archfiend06** [Newbrict/ObjHunt#85]
when you are props you are in first person mode and when you uncloak (using ULX) you are a Dr kliener with a black face. any ideas on how to fix this issue?

**Comment by Newbrict** [comment]
uh, I'm not sure what ULX does but it's probably interfering with how objhunt handles players. I can't look into ULX right, if you can give me more info that would be good

**Comment by Newbrict** [comment]
if you record a video of what you're talking about that would be optimal
