### ISSUE TITLE
Hard to become a prop

### ISSUE THREAD

**Issue by DutchPatrick** [Newbrict/ObjHunt#86]
I aim on props but only a small amount of them i can change into.
Everyone has this problem in the my server

**Comment by DutchPatrick** [comment]
In First Person it works fine, but third person...

**Comment by Newbrict** [comment]
Hi please add me on steam: newbrict

I have a feeling this is not an issue with objhunt itself but with your setup

**Comment by Newbrict** [comment]
The issue is you need to update to the latest objhunt!
