### ISSUE TITLE
Gamemode doesnt show in bottem right tab

### ISSUE THREAD

**Issue by Stickymitts** [Newbrict/ObjHunt#93]
Since a few days ago the obj hunt gamemode hasn't been in my gamemodes, I have tried reinstalling it and enabling/disabling it but nothing works, Please fix this, makes servers easier

**Comment by Newbrict** [comment]
Hi stickymitts... I've made the game by default show up as prop hunt, this is to aid in the popularity of dedicated servers.

I highly recommend running a dedicated server of your own, it is very easy to set up despite what other people say :)

I am still in debate whether or not to keep this "feature" 

GL
